### ISSUE TITLE
Help! I cannot build it on vercel

### ISSUE THREAD

**Issue by black-fruit** [willgibs/Chatpad-AI#1]
Look at the pic

<img width="1912" alt="截屏2023-04-13 12 51 18" src="https://user-images.githubusercontent.com/77201076/231656895-3549cade-578d-47a4-8b10-ef134c209f40.png">

**Comment by brown-sussy** [comment]
<img width="1912" alt="截屏2023-04-13 12 55 15" src="https://user-images.githubusercontent.com/77201076/231657218-2cc6721e-9c15-4cba-a5b7-d108684f3d87.png">

**Comment by willgibs** [comment]
Try deploying with the 'Parcel' framework preset with the default build settings - let me know if that works!

**Comment by willgibs** [comment]
It looks like the one-click Vercel deployment defaults to building with Next - will look into it tomorrow! In the meantime, try forking or cloning the repository and importing it from GitHub into Vercel with the Parcel framework preset.

**Comment by brown-sussy** [comment]
And look at this

<img width="1912" alt="截屏2023-04-13 17 42 06" src="https://user-images.githubusercontent.com/77201076/231720461-c2aa1317-e13b-47a4-a4a6-4b302df9e8bd.png">

**Comment by brown-sussy** [comment]
However, it looks is the code's bug, why you actually can build it. UwU

**Comment by willgibs** [comment]
https://user-images.githubusercontent.com/128860054/231794054-df6be996-18c8-4b74-b29c-fedb5cf71a17.mp4

Try this: import a new repository to your account by cloning 'Chatpad-AI', connect Vercel to your GitHub account, import your version of the 'Chatpad-AI' repository, and build it with the Parcel framework preset. If you try to deploy it with Next.js (most deployments automatically default to it), the build will fail.

**Comment by brown-sussy** [comment]
Okay, it fine, and can I send this video to bilibili(a Chinese video site)

**Comment by willgibs** [comment]
No problem! If it gets published, I'd love to see the link
