### ISSUE TITLE
Why add google tracker if you mention Privacy focused?

### ISSUE THREAD

**Issue by darth-pika-hu** [willgibs/Chatpad-AI#2]
```
> <!-- Google tag (gtag.js) -->
> --
> <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZLH3FM7WT5"></script>
> <script>
```

Why did you add google tracker if you mention Privacy focused?

**Comment by willgibs** [comment]
Just wanted to get a quick idea of traffic and decide whether or not it was worth expanding the app - aside from general page events, all data is still 100% private.

I'll be removing it soon but anyone looking to fork/clone the repo can remove it very easily.
