### ISSUE TITLE
List of chats

### ISSUE THREAD

**Issue by enisoru** [willgibs/Chatpad-AI#3]
Hello, why when i send message in chat, this chat disappeared form list?

**Comment by willgibs** [comment]
Could you elaborate or send a video with the issue?

**Comment by enisoru** [comment]
https://vimeo.com/820283178?share=copy

**Comment by enisoru** [comment]
i think it's mine problem, but don't understand why) in private browser no problem with that)

**Comment by willgibs** [comment]
The issue is likely the private browser - since all data is stored locally within your browser for privacy, private browsing is probably preventing some part of that data from being saved.

Will look into it!
